services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=kiss'
      - 'POSTGRES_PASSWORD=kiss'
      - 'POSTGRES_USER=kiss'
    labels:
      org.springframework.boot.jdbc.parameters: 'reWriteBatchedInserts=true'
    ports:
      - '5432'
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_URI=postgres:5432/kiss?sslmode=disable
      - DATA_SOURCE_USER=kiss
      - DATA_SOURCE_PASS=kiss
    ports:
      - '9187:9187'
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - '6379'
  # loki
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=kiss
      - GF_SECURITY_ADMIN_PASSWORD=kiss
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
  # minio
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=kiss
      - MINIO_ROOT_PASSWORD=kisskiss
    command: server /data
