services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=kiss'
      - 'POSTGRES_PASSWORD=kiss'
      - 'POSTGRES_USER=kiss'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
