services:
  app:
    image: 'kiss:0.0.1-SNAPSHOT'
    ports:
      - '9000:9000'
    depends_on:
      - postgres
      - redis
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=kiss'
      - 'POSTGRES_PASSWORD=kiss'
      - 'POSTGRES_USER=kiss'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
