jimmer:
  language: kotlin
  client:
    openapi:
      properties:
        info:
          title: Kiss
          version: 1.0.0
          description: Keep It Simple Stupid
      ui-path: /openapi.html
      path: /openapi.yml
    ts:
      path: /ts.zip
      mutable: true
  mutation-transaction-required: true
  database-validation-mode: error
  show-sql: true
spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  port: 9000
