global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: postgres
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - postgres-exporter:9187
  - job_name: kiss
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:8001