jimmer:
  language: kotlin
  client:
    openapi:
      properties:
        info:
          title: Kiss
          version: 1.0.0
          description: Keep It Simple Stupid
      ui-path: /openapi.html
      path: /openapi.yml
    ts:
      path: /ts.zip
      mutable: true
  mutation-transaction-required: true
  database-validation-mode: error
  #  show-sql: true
  #  pretty-sql: true
  #  inline-sql-variables: true
  executor-context-prefixes:
    - kiss
  default-dissociation-action-checkable: false
spring:
  application:
    name: kiss
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 8001
logging:
  level:
    kiss.authentication: debug
  file:
    name: ${user.home}/logs/kiss.log
minio:
  endpoint: http://localhost:9000
  access-key: kiss
  secret-key: kisskiss
